### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by danielecook** [ewels/AWS-iGenomes#1]
I am getting access denied when running locally, and on AWS. I have AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY exported in my env; Any idea why this might not be working?

```
aws s3 --region eu-west-1 sync s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/build37.2/Sequence/WholeGenomeFasta/ .
fatal error: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
```

**Comment by ewels** [comment]
Hi @danielecook,

Sorry to hear that you're having problems with these. I just checked and I can still see the files (which means that I haven't accidentally deleted them or anything stupid):

```
$ aws s3 --region eu-west-1 ls s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/build37.2/Sequence/WholeGenomeFasta/

2017-04-13 16:30:35       4237 GenomeSize.xml
2017-04-13 16:30:36       3950 genome.dict
2017-04-13 16:30:36 3139918279 genome.fa
2017-04-13 16:30:40        714 genome.fa.fai
```

I also tried copying and pasting your command and that worked too.

The bucket is definitely set to allow public read-only access:

![aws-perms](https://user-images.githubusercontent.com/465550/31166228-4da455ec-a8ee-11e7-9c95-9771c27ef1a8.png)

Note that the bucket is set to [Requester Pays](https://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html), so that may affect some kind of AWS permissions that you have set up?

What happens when you try to `ls` that path instead of `sync`?
I assume that working with your own files on s3 works fine?

Phil

**Comment by ewels** [comment]
Note that I have my aws permissions set up slightly differently, using `~/.aws` instead of environment variables. Though that shouldn't make any difference..

```
==> .aws/config <==
[default]
region = eu-west-1

==> .aws/credentials <==
[default]
aws_access_key_id = XXXXX
aws_secret_access_key = xxxxxxx
```

**Comment by ewels** [comment]
Hmm, other people I've asked here also are having problems accessing the files apparently, so it's probably something I've done wrong. I'll look into it more and get back to you.

**Comment by ewels** [comment]
Hi @danielecook,

I think that we've figured it out.. It looks like the AWS CLI has a (possibly new?) command line flag called `--request-payer`:

> `--request-payer` (string) Confirms that the requester knows that she  or
> he will be charged for the request. Bucket owners need not specify this
> parameter in their requests. Documentation on downloading objects  from
> requester       pays       buckets       can      be      found      at
> http://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectsinRequesterPaysBuckets.html

I don't need this as it's my bucket, however other people had the permission denied error until they added that command line flag:

```
aws s3 --region eu-west-1 ls --request-payer requester s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/build37.2/Sequence/WholeGenomeFasta/
```

I guess the same will be true with the `sync` command. I'll update the docs / website accordingly. Let me know how you get on!

Phil

**Comment by ewels** [comment]
Docs and scripts updated in 6953783a7ed9255f5273b9ff857f7dd9c5ade684

**Comment by danielecook** [comment]
I run this and get an error:

```
aws s3api get-object --region eu-west-1 --request-payer requester --bucket ngi-igenomes --key igenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa .

An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
```

**Comment by danielecook** [comment]
Hey @ewels - To summarize:

You need to be sure the 'requester-pays' option is set:

![screen shot 2017-10-05 at 6 27 27 pm](https://user-images.githubusercontent.com/1536935/31256910-e953e6a8-a9fa-11e7-8412-450a508af2b5.png)

And...I'm not sure if s3 cp works with this bit if it doesn't you can use the `aws s3api` alternatively. These changes will need to be applied to the nextflow pipelines too. Can you confirm that that option is set correctly?

**Comment by ewels** [comment]
Hi @danielecook,

Yes, requester pays is set as in the screenshot (except set to "Enabled"). The Nextflow but may be more complicated though as it uses built in s3 support. 

Phil

**Comment by ewels** [comment]
Thanks for testing this by the way - it's surprisingly difficult when all of my amazon accounts have full access!

**Comment by danielecook** [comment]
The other thing you can try is setting up the bucket policy and being sure that it has the  'GetObject'  permission.

**Comment by Hammarn** [comment]
I also gave this a try and recieved the following error:
```
aws s3 sync --region eu-west-1 --request-payer requester  s3://ngi-igenomes/igenomes/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/ ./references/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/

Unknown options: --request-payer,./references/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/
```

**Comment by ewels** [comment]
Hi @danielecook,

I got a reply from Jed at AWS who suggested using s3api as you tried above. We still have plenty of Amazon credits left from the grant they gave to support this though, so for now I've just opened up access to everyone and removed the _Requester Pays_ policy. I'll monitor how our costs go for a while and we can go for there. So not a super long-term solution I'm afraid, but it should be available for a few months at least now.

Let me know how you get on!

Phil

**Comment by danielecook** [comment]
Thanks Phil. I’m going to play around with it to and see if I can figure it
out.

**Comment by ewels** [comment]
Potential better solution suggested by Brendan B - using an access control list to allow full access to anyone in the same region. Transfers within the region should be free (right?) and access would still be easy then.

Phil

**Comment by veeravalli** [comment]
Hi Phil,
I am trying to download a gtf file. " ls" works but I get the access error when I try to "cp" or "sync" 
aws s3 --region eu-west-1 sync s3://ngi-igenomes/igenomes/Oryza_sativa_japoni
ca/Ensembl/IRGSP-1.0/Annotation/Genes/ /mnt/projects/rpd/devs/lavanya/test/ --exclude "*" --include "genes.gtf"
download failed: s3://ngi-igenomes/igenomes/Oryza_sativa_japonica/Ensembl/IRGSP-1.0/Annotation/Genes/genes.gtf to test/genes.gtf An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
Have you given full access to S3 bucket in teh same region? Probably I can try that. Thanks.

**Comment by ewels** [comment]
Hi @veeravalli,

Thanks for your comment - I had hoped that I wouldn't need to bother with a `GetObject` policy since I made the bucket public for everyone, this is annoying.

I can confirm that if I try your command with no credentials and `--no-sign-request`. I'll look into this (much easier when I can replicate / test myself!)

Phil

**Comment by ewels** [comment]
Hi @veeravalli,

I've just added a new bucket policy which should allow `GetObject`. I've tested without authentication and it works for me now. Let me know how you get on!

@danielecook - may be worth another go now too!

Thanks,

Phil

**Comment by veeravalli** [comment]
Hi @ewels ,
Thanks. It works now :)
Lavanya

**Comment by ewels** [comment]
Ok brilliant - working at last! Thanks!
