### ISSUE TITLE
Bowtie index for alternative haplotype in hg19

### ISSUE THREAD

**Issue by jennymoon90** [ewels/AWS-iGenomes#10]
Hi,
I have a question about the haplotype information in hg19. Are both H1 and H2 haplotypes of the MAPT locus (chr17q21.31 region) included in the iGenome hg19 version? If not, how may I create bowtie index for the H2 haplotype? 
Appreciate your help.
Jenny

**Comment by ewels** [comment]
Hi Jenny,

I’m afraid I have no idea, but the data is all open so you should be able to grab a copy yourself and find out.

Phil
