### ISSUE TITLE
The future of AWS-iGenomes

### ISSUE THREAD

**Issue by David-J-R** [ewels/AWS-iGenomes#11]
I'm currently planning on including the AWS-iGenomes script into a RNA-seq pipeline I'm working on. As I read that the data-set is however only hosted until 30 January 2021 with hope of renewal of the agreement, the question for me came up, if there's an alternative plan to host the data-set and keep the script working, if AWS doesn't renew the current agreement.

This is important for my consideration, if I should or should not include the script into my pipeline for obvious reasons. And I could imagine that this question could be important for other users as well.

**Comment by ewels** [comment]
Hi @David-J-R - great that you reminded me of this! I have dropped an email to the people at AWS who helped me set this up to see if we can extend that date.

I personally have no plans to take down AWS-iGenomes and haven't heard anything along those lines, so hopefully it will stay up as it is for the foreseeable future. 🤞🏻 

Phil

**Comment by ewels** [comment]
I'm happy to say that we are now safe until 28th Oct 2022:

> AWS will continue to sponsor up to 8 TB of data storage for the iGenomes dataset for a period of two years from 10/28/2020.

Thank you AWS! 🎉  I'll update the readme now..
