### ISSUE TITLE
Bulk download for a species

### ISSUE THREAD

**Issue by adomingues** [ewels/AWS-iGenomes#12]
Hi Phill,

first of all thank you for setting up this super practical resource. My question is comes from the fact that for any given pipeline / analysis, a number of references is needed for a species. For instance `nf-core/rnaseq` uses iirc genome sequence, STAR+RSEM+salmon indexes, GTF, etc.

Since downloading each one individually is quite tedious, Is it possible to get the full datasets for a particular species? Say for human? An example would be if this command `bash aws-igenomes.sh -g Homo_sapiens -s Ensembl -b GRCh37` would download all indexes for `Ensembl/GRCh37` instead of asking for `-t`.

I guess another alternative would be for me to download from iGenomes directly and produce the missing indexes :)

Cheers,
António

**Comment by adomingues** [comment]
I looked up the source code of the function and got how to do it:

```bash
aws s3 --no-sign-request --region eu-west-1 sync s3://ngi-igenomes/igenomes/Escherichia_coli_K_12_DH10B/Ensembl/EB1/ $(pwd)/references/Escherichia_coli_K_12_DH10B/Ensembl/EB1/
```

Cheers.

**Comment by ewels** [comment]
Ah you beat me to it, yup that's the one!

You should be able to build a sync command like this on the helper page https://ewels.github.io/AWS-iGenomes/ (eg. for type FASTA) and then just cut back to whatever directory it is that you want to sync.
