### ISSUE TITLE
Salmo_salar (Atlantic Salmon) ref?

### ISSUE THREAD

**Issue by marwa38** [ewels/AWS-iGenomes#14]
Hello 

Could you please add Atlantic salmon (salmo salar) to the references so that I could easily use it via AWS-iGenomes references in nf-core? on Ensembl: https://www.ensembl.org/Salmo_salar/Info/Index
(ICSASG_v2 (GCA_000233375.4)

Thanks 
Marwa

**Comment by ewels** [comment]
Hi @marwa38,

You can use any custom genome within nf-core pipelines without them being in AWS-iGenomes. See the documentation for how to do this here: https://nf-co.re/usage/reference_genomes#adding-paths-to-a-config-file

We are hoping to move away from using AWS-iGenomes in the near future and I consider it to be in maintenance mode only now. I will do my best to keep it online for as long as possible for the sake of reproducibility, but I am not intending to add any new references.

Let me know if you need any further help,

Phil
