### ISSUE TITLE
What are the versions of genome files?

### ISSUE THREAD

**Issue by hyjforesight** [ewels/AWS-iGenomes#17]
Hello AWS-iGenomes,
Thanks for making this database.
I'm using nf-core ATAC-seq pipeline now. On the introduction page, nf-core says they are using the files of this database as their reference genomes (https://ewels.github.io/AWS-iGenomes/) for alignment.
I'm now facing an issue that, I need to use the bam files for downstream RGT-HINT analysis. The RGT-HINT package is using the gtf files of Gencode vM25 version (mouse) and Gencode v21 version (human). I believe their versions do not match with the versions of AWS-iGenomes, because I'm keeping receiving the error messages that the coordinates of genes do not match.

```python
# I believe the versions of AWS-iGenomes are not Gencode vM25 version (mouse) and Gencode v21 version (human), because the nf-core output file says:
The contents of the annotation directories were downloaded from UCSC on: July 17, 2015.
SmallRNA annotation files were downloaded from miRBase release 21.
```
```python
# I'm keeping receiving the error messages that the coordinates of genes do not match.
Report: The scikit HMM encountered errors when applied. in region (10,52417320,52418086). This iteration will be skipped.
```
The contents of the annotation directories were downloaded from UCSC on: July 17, 2015. Could you please tell me which version you downloaded at that time both for human (https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/) and mouse (https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/)?

Thanks!
Best,
Yuanjian

**Comment by ewels** [comment]
Hi @hyjforesight,

These references were originally fetched from the illumina iGenomes resource: https://emea.support.illumina.com/sequencing/sequencing_software/igenome.html

I didn't do the original downloads, so I'm afraid that I can't help much beyond pointing to the `README.txt` files found within the reference directories that have some information about where and when they were fetched.

Phil

**Comment by ewels** [comment]
Note that we are hoping to stop using AWS-iGenomes for @nf-core pipelines in the near(ish) future, to be replaced with @refgenie - see issue here: https://github.com/nf-core/tools/issues/1239
