### ISSUE TITLE
Manifest contains spaces in paths

### ISSUE THREAD

**Issue by andreas-wilm** [ewels/AWS-iGenomes#2]
Hi Phil,

Thanks for making this available!

ngi-igenomes_file_manifest.txt wrongly contains extra spaces (right after the bucket name) on 71 lines (mostly for STAR indices). The path without space is obviously the correct one.

Andreas

**Comment by ewels** [comment]
Great spot, thanks Andreas! That's weird - I thought I had generated it with a single command.. Anyway, should be easy to fix.
